main = "./src/index.ts"
name = "kurva-r2"
compatibility_date = "2022-07-26"
account_id = "88018ab33f1bd7fcbd871efd4776caa5"

[[r2_buckets]]
binding = "TESTING_R2_KURVA"
bucket_name = "testing-r2-kurva"